### PR TITLE
fix: #11 Code Coverage

### LINKED ISSUE #11: Coverage is too low
Currently at 65%. 
We should aim for 85% or more.
~~Codecov is the quality gate for coverage. As per [docs](https://docs.codecov.io/docs/codecov-yaml#section-default-yaml) the `.codecov.yaml` can be added at the repo or org level.~~
We were not including the codecov checks in PRs. That has been fixed.

**We need to fix coverage in `internal/crypto/utils`**

### PR DESCRIPTION
**Pull request by llorllale**
Fixes #11 

* Removed unused code in `internal/crypto/utils`
* Removed check for error messages in the tests since there are no dependency on the contents of these messages

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

File: internal/crypto/utils_test.go [hunk 1]
```diff
@@ -1,14 +1,13 @@
 /*
-   Copyright SecureKey Technologies Inc.
-   This file contains software code that is the intellectual property of SecureKey.
-   SecureKey reserves all rights in the code and you may not use it without written permission from SecureKey.
+  copyright securekey technologies inc. all rights reserved.
```
Comment (troyronda) [inline internal/crypto/utils_test.go]: This copyright header should be capitalized the same as the other files.

Comment (troyronda) [reply internal/crypto/utils_test.go]: Example: https://github.com/trustbloc/fabric-peer-ext/blob/master/mod/peer/blkstorage/store.go

Comment (llorllale) [reply internal/crypto/utils_test.go]: @troyronda fixed
